### ISSUE TITLE
x264=20180501 breaks opencv 3.3.0 and 3.4.1

### ISSUE THREAD

**Issue by pgunn** [conda-forge/x264-feedstock#16]
The freshly-released version of x264 is pulled in by opencv (3.3.0) and breaks it on OSX

```
scclin009:~$ python
Python 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libx264.so.138: cannot open shared object file: No such file or directory
```

Upgrading opencv to 3.4.1 did not help.

**Comment by pgunn** [comment]
Will possibly be fixed by https://github.com/conda-forge/ffmpeg-feedstock/pull/48

**Comment by hajapy** [comment]
Can confirm, this has bit us as we are using opencv 3.3.0.

**Comment by carlodri** [comment]
is the issue solved if you downgrade `x264`?

**Comment by hajapy** [comment]
Yes, adding in hard pins to prior x264 fixes things, though we have many built packages that wouldn't have that pin and so they are all effectively broken.

**Comment by pgunn** [comment]
I tried pinning the old version of x264 yesterday with our project; we're trying to have a single recommended environment.yml for our project that works across OSX, Windows, and Linux. If I recall correctly, older versions of x264 were available for pinning on Linux and OSX but the Windows versions were not versioned the same way so it didn't work.

If it's important, I can dig out more details. LMK.

**Comment by pgunn** [comment]
Hi,
The change to ffmpeg-feedstock didn't seem to do the trick.
I propose marking the newer x264 builds as broken so nobody gets them, until people get the time to reach consensus on how to work through the ffmpeg/x264 brokenness and actually have a solution in hand, as right now conda-forge users (including users of projects that use conda as their preferred env) using these packages are seeing brokenness.

**Comment by marcelotrevisani** [comment]
is it just in osx?

**Comment by jakirkham** [comment]
Think it is Linux too.

**Comment by pgunn** [comment]
It is definitely Linux too.

**Comment by sdvillal** [comment]
It should now be fixed. I close this, please reopen if it happens again.
