### ISSUE TITLE
Error parsing URL with "!" in it

### ISSUE THREAD

**Issue by agstephens** [conda-forge/x264-feedstock#24]
Issue:

I am trying to install an environment containing `x264` that uses `--file <url-to-file-containing-package urls>`. 

When conda tries to parse the spec line for x264 it says:

```
CondaValueError: could not parse 'http://dist.ceda.ac.uk/jaspy/jaspy3.7/m3-4.7.10/linux-64/x264-1!152.20180806-h14c3975_0.tar.bz2' in: ./bin/../environments-ceda-jaspy-envs/py3.7/m3-4.7.10/jaspy3.7-m3-4.7.10-r20191126/channel-urls.txt
```

I can hack the conda library to overcome this but the error is due to a regex that doesn't like the `!` character in the spec (URL), in:

`conda/cli/common.py`

Could you remove the `!` from the URL in the next version? Thanks

**Comment by sdvillal** [comment]
! cannot be removed (it indicates the version epoch). Please open an issue against conda.

**Comment by agstephens** [comment]
Thanks @sdvillal , I'll do that.
